// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoaFp7vYbzfRsoJIMQB9w4pq1kxwarVg4',
    appId: '1:301834009254:web:2612025447fc6abcf19267',
    messagingSenderId: '301834009254',
    projectId: 'fir-assignment-45cb6',
    authDomain: 'fir-assignment-45cb6.firebaseapp.com',
    storageBucket: 'fir-assignment-45cb6.firebasestorage.app',
    measurementId: 'G-G7QBXBT71W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Zjz993ySu9DRCCsd0SXn6ZBnbbF5TpM',
    appId: '1:301834009254:android:a803e9bd2e8ad055f19267',
    messagingSenderId: '301834009254',
    projectId: 'fir-assignment-45cb6',
    storageBucket: 'fir-assignment-45cb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbtgVegeBae5abGnGiP9LoHutqvIFs9Sc',
    appId: '1:301834009254:ios:f10f0de05a51acfcf19267',
    messagingSenderId: '301834009254',
    projectId: 'fir-assignment-45cb6',
    storageBucket: 'fir-assignment-45cb6.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbtgVegeBae5abGnGiP9LoHutqvIFs9Sc',
    appId: '1:301834009254:ios:f10f0de05a51acfcf19267',
    messagingSenderId: '301834009254',
    projectId: 'fir-assignment-45cb6',
    storageBucket: 'fir-assignment-45cb6.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoaFp7vYbzfRsoJIMQB9w4pq1kxwarVg4',
    appId: '1:301834009254:web:f7938d10af0bb78af19267',
    messagingSenderId: '301834009254',
    projectId: 'fir-assignment-45cb6',
    authDomain: 'fir-assignment-45cb6.firebaseapp.com',
    storageBucket: 'fir-assignment-45cb6.firebasestorage.app',
    measurementId: 'G-1CH4RZSFJY',
  );
}
